name: Mirror Repository

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mirror Push to Client Repo
        env:
          TARGET_REPO: "https://github.com/bikelpg/bike10.git"  # Confirm this URL is correct
          TARGET_TOKEN: ${{ secrets.CLIENT_TOKEN }}
        run: |
          git remote add mirror https://$TARGET_TOKEN@github.com/bikelpg/bike10.git
          git push mirror --mirror
