name: Sync to Client Repository

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Add client remote
        run: |
          git remote add client https://${{ secrets.CLIENT_PAT }}@github.com/bikelpg/bikelpg20.git
          
      - name: Push to client repository
        run: |
          git push client main:main --force
          
      - name: Notify on success
        if: success()
        run: echo "Successfully synced repository to client's GitHub"
        
      - name: Notify on failure
        if: failure()
        run: echo "Failed to sync repository"
